### ISSUE TITLE
ceres maintenance rollup issue

### ISSUE THREAD

**Issue by anatolijd** [graphite-project/ceres#6]
Hi,
I'm trying to understand ceres-maintenance as it is completely undocumented, and I've got multiple issues with rollup plugin.
I've got about 20 slice files (*@10.slice) per node during two weeks, and I decided to defrag them (remove slice gaps) and archive them (to the next lower resolution @60.slice).

This is a test server, which has just a bit less than 500 metric collected.  Only 300 of them are being sent from single collectd daemon with 10 sec interval. 

I started rollup and I was surprized by the fact that  it took 5 hours to complete.

```
# ceres-maintenance  --configdir=$CONF_DIR/writer-1 rollup --log=rollup.log
real  310m32.189s
user  309m2.727s
sys 0m33.202s
```

In the log file I found many errors like this.

```
[Thu Jun  6 11:12:10 2013]  --- Error in node_found event-handler ---
[Thu Jun  6 11:12:10 2013]  Traceback (most recent call last):
  File "/opt/graphite/bin/ceres-maintenance", line 95, in dispatch
    handler(*args, **kwargs)
  File "/opt/graphite/plugins/maintenance/rollup.py", line 61, in node_found
    do_rollup(node, archive, archives[i+1])
  File "/opt/graphite/plugins/maintenance/rollup.py", line 102, in do_rollup
    coarseValue = aggregate(node, fineDatapoints)
  File "/opt/graphite/plugins/maintenance/rollup.py", line 22, in aggregate
    return float(sum(values)) / len(values) # values is guaranteed to be nonempty
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

I've found the reason and fixed the aggregate() function locally, but it did not help much.
Also, I noticed that some nodes are processed fast (less than 2sec), while other nodes need minutes and even tens of minutes to process. I made logs more verbose.

Here is a part of the log, you may see two nodes found and being porocessed:

node_found node:collectd.redfish.interface-vboxnet0.if_errors.tx
node_found node:collectd.redfish.interface-vboxnet0.if_errors.rx

and there was 43200 iterations performed in do_rollup loop for both.
(because my next retention is [60,43200]).

But, 
- node_found node:collectd.redfish.interface-vboxnet0.if_errors.tx  - all 43200 iterations were completed within 2 seconds, 
- node_found node:collectd.redfish.interface-vboxnet0.if_errors.rx -  about 14 seconds to perform just 1000 iterations.

```
[Thu Jun  6 11:06:38 2013]  node_found: collectd.redfish.interface-vboxnet0.if_errors.tx
[Thu Jun  6 11:06:38 2013]  archive 0: retention:8640, startTime:1370444790, endTime:1370531190, slices:1
[Thu Jun  6 11:06:38 2013]  do_rollup:: collectd.redfish.interface-vboxnet0.if_errors.tx, 1370444790
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1367852820, windowEnd: 1367852880, fineDatapoints: 0, 1/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1367912820, windowEnd: 1367912880, fineDatapoints: 0, 1001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1367972820, windowEnd: 1367972880, fineDatapoints: 0, 2001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368032820, windowEnd: 1368032880, fineDatapoints: 0, 3001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368092820, windowEnd: 1368092880, fineDatapoints: 0, 4001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368152820, windowEnd: 1368152880, fineDatapoints: 0, 5001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368212820, windowEnd: 1368212880, fineDatapoints: 0, 6001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368272820, windowEnd: 1368272880, fineDatapoints: 0, 7001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368332820, windowEnd: 1368332880, fineDatapoints: 0, 8001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368392820, windowEnd: 1368392880, fineDatapoints: 0, 9001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368452820, windowEnd: 1368452880, fineDatapoints: 0, 10001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368512820, windowEnd: 1368512880, fineDatapoints: 0, 11001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368572820, windowEnd: 1368572880, fineDatapoints: 0, 12001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368632820, windowEnd: 1368632880, fineDatapoints: 0, 13001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368692820, windowEnd: 1368692880, fineDatapoints: 0, 14001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368752820, windowEnd: 1368752880, fineDatapoints: 0, 15001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368812820, windowEnd: 1368812880, fineDatapoints: 0, 16001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368872820, windowEnd: 1368872880, fineDatapoints: 0, 17001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368932820, windowEnd: 1368932880, fineDatapoints: 0, 18001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1368992820, windowEnd: 1368992880, fineDatapoints: 0, 19001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369052820, windowEnd: 1369052880, fineDatapoints: 0, 20001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369112820, windowEnd: 1369112880, fineDatapoints: 0, 21001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369172820, windowEnd: 1369172880, fineDatapoints: 0, 22001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369232820, windowEnd: 1369232880, fineDatapoints: 0, 23001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369292820, windowEnd: 1369292880, fineDatapoints: 0, 24001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369352820, windowEnd: 1369352880, fineDatapoints: 0, 25001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369412820, windowEnd: 1369412880, fineDatapoints: 0, 26001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369472820, windowEnd: 1369472880, fineDatapoints: 0, 27001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369532820, windowEnd: 1369532880, fineDatapoints: 0, 28001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369592820, windowEnd: 1369592880, fineDatapoints: 0, 29001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369652820, windowEnd: 1369652880, fineDatapoints: 0, 30001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369712820, windowEnd: 1369712880, fineDatapoints: 0, 31001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369772820, windowEnd: 1369772880, fineDatapoints: 0, 32001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369832820, windowEnd: 1369832880, fineDatapoints: 0, 33001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369892820, windowEnd: 1369892880, fineDatapoints: 0, 34001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1369952820, windowEnd: 1369952880, fineDatapoints: 0, 35001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370012820, windowEnd: 1370012880, fineDatapoints: 0, 36001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370072820, windowEnd: 1370072880, fineDatapoints: 0, 37001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370132820, windowEnd: 1370132880, fineDatapoints: 0, 38001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370192820, windowEnd: 1370192880, fineDatapoints: 0, 39001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370252820, windowEnd: 1370252880, fineDatapoints: 0, 40001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370312820, windowEnd: 1370312880, fineDatapoints: 0, 41001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370372820, windowEnd: 1370372880, fineDatapoints: 0, 42001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.tx, windowStart: 1370432820, windowEnd: 1370432880, fineDatapoints: 0, 43001/43200
[Thu Jun  6 11:06:38 2013]  do_rollup:: slice.write 1370363940@60
[Thu Jun  6 11:06:38 2013]  archive 1: retention:43200, startTime:1367852760, endTime:1370444760, slices:1
[Thu Jun  6 11:06:38 2013]  do_rollup:: collectd.redfish.interface-vboxnet0.if_errors.tx, 1367852760
[Thu Jun  6 11:06:38 2013]  archive 2: retention:105120, startTime:1336316700, endTime:1367852700, slices:0
[Thu Jun  6 11:06:38 2013]  do_rollup:: collectd.redfish.interface-vboxnet0.if_errors.tx, 1336316700

[Thu Jun  6 11:06:38 2013]  node_found: collectd.redfish.interface-vboxnet0.if_errors.rx
[Thu Jun  6 11:06:38 2013]  archive 0: retention:8640, startTime:1370444790, endTime:1370531190, slices:2
[Thu Jun  6 11:06:38 2013]  do_rollup:: collectd.redfish.interface-vboxnet0.if_errors.rx, 1370444790
[Thu Jun  6 11:06:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1367852820, windowEnd: 1367852880, fineDatapoints: 0, 1/43200
[Thu Jun  6 11:06:52 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1367912820, windowEnd: 1367912880, fineDatapoints: 0, 1001/43200
[Thu Jun  6 11:07:06 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1367972820, windowEnd: 1367972880, fineDatapoints: 0, 2001/43200
[Thu Jun  6 11:07:20 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368032820, windowEnd: 1368032880, fineDatapoints: 0, 3001/43200
[Thu Jun  6 11:07:33 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368092820, windowEnd: 1368092880, fineDatapoints: 0, 4001/43200
[Thu Jun  6 11:07:47 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368152820, windowEnd: 1368152880, fineDatapoints: 0, 5001/43200
[Thu Jun  6 11:08:01 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368212820, windowEnd: 1368212880, fineDatapoints: 0, 6001/43200
[Thu Jun  6 11:08:14 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368272820, windowEnd: 1368272880, fineDatapoints: 0, 7001/43200
[Thu Jun  6 11:08:28 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368332820, windowEnd: 1368332880, fineDatapoints: 0, 8001/43200
[Thu Jun  6 11:08:42 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368392820, windowEnd: 1368392880, fineDatapoints: 0, 9001/43200
[Thu Jun  6 11:08:55 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368452820, windowEnd: 1368452880, fineDatapoints: 0, 10001/43200
[Thu Jun  6 11:09:09 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368512820, windowEnd: 1368512880, fineDatapoints: 0, 11001/43200
[Thu Jun  6 11:09:22 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368572820, windowEnd: 1368572880, fineDatapoints: 0, 12001/43200
[Thu Jun  6 11:09:36 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368632820, windowEnd: 1368632880, fineDatapoints: 0, 13001/43200
[Thu Jun  6 11:09:50 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368692820, windowEnd: 1368692880, fineDatapoints: 0, 14001/43200
[Thu Jun  6 11:10:03 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368752820, windowEnd: 1368752880, fineDatapoints: 0, 15001/43200
[Thu Jun  6 11:10:17 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368812820, windowEnd: 1368812880, fineDatapoints: 0, 16001/43200
[Thu Jun  6 11:10:30 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368872820, windowEnd: 1368872880, fineDatapoints: 0, 17001/43200
[Thu Jun  6 11:10:44 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368932820, windowEnd: 1368932880, fineDatapoints: 0, 18001/43200
[Thu Jun  6 11:10:57 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1368992820, windowEnd: 1368992880, fineDatapoints: 0, 19001/43200
[Thu Jun  6 11:11:11 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1369052820, windowEnd: 1369052880, fineDatapoints: 0, 20001/43200
[Thu Jun  6 11:11:24 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1369112820, windowEnd: 1369112880, fineDatapoints: 0, 21001/43200
[Thu Jun  6 11:11:38 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1369172820, windowEnd: 1369172880, fineDatapoints: 0, 22001/43200
[Thu Jun  6 11:11:52 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1369232820, windowEnd: 1369232880, fineDatapoints: 0, 23001/43200
[Thu Jun  6 11:12:05 2013]  do_rollup:: node:collectd.redfish.interface-vboxnet0.if_errors.rx, windowStart: 1369292820, windowEnd: 1369292880, fineDatapoints: 0, 24001/43200
[Thu Jun  6 11:12:10 2013]  do_rollup:: slice.write 1369312440@60
...
```

Here are the file sizes:

```
ll /opt/graphite/storage/ceres/collectd/redfish/interface-vboxnet0/if_errors/*/*slice
-rw-r--r-- 1 root root 160760 Jun  7 09:26 /opt/graphite/storage/ceres/collectd/redfish/interface-vboxnet0/if_errors/rx/1369312440@60.slice
-rw-r--r-- 1 root root  20560 Jun  7 07:49 /opt/graphite/storage/ceres/collectd/redfish/interface-vboxnet0/if_errors/tx/1370363940@60.slice
```

rx is 8 times bigger that tx  but I hardly believe this can explain the situation.

Any ideas why it is so or what to do to find a reason of this ?

**Comment by deniszh** [comment]
https://github.com/dkulikovsky/carbon/tree/megacarbon/plugins/maintenance should be ported here
